name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: sudo apt-get install gcc-avr -y
    - name: Checkout code
      uses: actions/checkout@v2
    - name: build
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
